### ISSUE TITLE
Script for automatically synchronizing the template.properties file to other files

### ISSUE THREAD

**Issue by AutumnPizazz** [AutumnPizazz/the-Coexistence-in-harmony#18]
@SomeTroglodyte 
I am frustrated because I do not have a convenient script as described in the title to assist me in updating translation files.
You see, I have little to no programming foundation and it is difficult for me to find helpful resources on the internet, even asking GPT doesn't help. That is why I am seeking your assistance.
Please!Please!

**Comment by SomeTroglodyte** [comment]
You open the _desktop_ app, go to Options Advanced, and use the "Generate Translation Files" button there... Will also sync for mods, but with a few special rules - as far as i remember that will write stuff the mod's jsons contain - but the base translations do not already cover - into existing translation files only. Is that what you mean? template.properties is only relevant to the base game, not mods. Should also be documented somewhere in the wiki (could be worth a bug report if it is not). Lastly, the functionality exists for desktop only, not android, because on 'droid the majority of the translations live inside the apk and wouldn't be writable anyway. Opening that translation writer stuff on Android and build enough switches into it that it treats mods only would be thinkable, but AFAIK wasn't worth the effort so far. After all, _everybody_ has a PC somewhere :innocent:

**Comment by AutumnPizazz** [comment]
This feature is so cool! But it's not well-matched with the translation files of my module, so I'll need to spend some time adapting it.

**Comment by AutumnPizazz** [comment]
<img width="1280" alt="image" src="https://github.com/AutumnPizazz/CoeHarMod/assets/114050365/74ea408d-3051-4f80-bde3-a747fea09aeb">
In my VScode, the parts enclosed in single quotes are marked in orange, which bothers me. At the same time, I can't find a way to disable this rule. Can you help me?

**Comment by SomeTroglodyte** [comment]
> Can you help me

Nope, haven't the foggiest about VScode. It is seeing the single quote as special - no idea how or if or where VScode is configurable to see it as text instead. In some editors, you tell it "that's an ini file" and may have luck... Or tell it to treat all .properties files as generic text, no syntax highlighting rules.
